"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$username"""

[character] # The name of the module we are configuring is "character"
success_symbol = "[\\[I\\]](white) [](bold yellow)[](bold purple)[](bold green) [](bold blue) "
error_symbol = "[\\[I\\]](white) [](bold yellow)[](bold purple)[](bold green) [](bold red) "
vimcmd_symbol = "[\\[N\\]](white) [](bold yellow)[](bold purple)[](bold green) [](bold blue) "

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[](#f2cdcd)[$user](fg:#181825 bg:#f2cdcd)[](#f2cdcd) '
disabled = false
show_always = true


